CREATE TABLE IF NOT EXISTS `Task` (
  `event_id` INT(8) ZEROFILL NOT NULL,
  `desc` VARCHAR(512) NOT NULL,
  `time` INT(7) NOT NULL DEFAULT 0,
  `isDone` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`event_id`),
  CONSTRAINT `FK3`
    FOREIGN KEY (`event_id`)
    REFERENCES `Event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;